function T_loss = EQDynamicAnalysis(T,GMfile,Scaling,SCFactor)

current_dir = cd;
cd('..\python lib\MDOFModel');
command = ['python Tool_LossAssess.py', ...
    ' --NumofStories  ', num2str(T{1,'NumberOfStories'}), ...
    ' --FloorArea ', num2str(T{1,'PlanArea'}), ...
    ' --StructuralType ',  T{1,'StructureType'}{1}, ...
    ' --OccupancyClass ', T{1,'OccupancyClass'}{1}, ...
    ' --EQRecordFile ', GMfile , ...
    ' --EQScaling ', num2str(Scaling), ...
    ' --DesignLevel ', T{1,'DesignLevel'}{1}, ...
    ' --SelfCenteringEnhancingFactor ', num2str(SCFactor)]; 
status = system(command);

T_loss = readtable(fullfile('BldLoss.csv'));

cd(current_dir);

end

