function IDA(IM_list,NumofStories,FloorArea,StructuralType, ...
    OccupancyClass, DesignLevel, EQMetaDataFile, OutputCSVFile, ...
    SelfCenteringEnhancingFactor)

current_folder = cd;
cd('..\python lib\MDOFModel');

command = ['python Tool_IDA.py --IM_list ',num2str(IM_list), ...
    ' --NumofStories ', num2str(NumofStories), ...
    ' --FloorArea ', num2str(FloorArea), ...
    ' --StructuralType ', StructuralType, ...
    ' --OccupancyClass ', OccupancyClass, ...
    ' --DesignLevel ', DesignLevel, ...
    ' --EQMetaDataFile ', EQMetaDataFile, ...
    ' --OutputCSVFile ', OutputCSVFile, ...
    ' --SelfCenteringEnhancingFactor ', num2str(SelfCenteringEnhancingFactor)];
status = system(command);

cd(current_folder);

end

